-- Group name:   A01_Group015
-- Group member:Meshaal Alenezi, Nidhi Chowdary Gadde, Sirui Huang
-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-14 12:29:30 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
spool pf_schema_output.txt

DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE pet_type CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE specialisation CASCADE CONSTRAINTS;

DROP TABLE train_vet CASCADE CONSTRAINTS;

DROP TABLE training CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

DROP TABLE visit_drug CASCADE CONSTRAINTS;

DROP TABLE visit_service CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clinic (
    clinic_id       NUMBER(2) NOT NULL,
    clinic_name     VARCHAR2(50) NOT NULL,
    clinic_phone_no NUMBER(10) NOT NULL,
    clinic_address  VARCHAR2(100) NOT NULL,
    vet_id          NUMBER(2) NOT NULL
);

COMMENT ON COLUMN clinic.clinic_id IS
    'the clinic id number';

COMMENT ON COLUMN clinic.clinic_name IS
    'the name of the clinic';

COMMENT ON COLUMN clinic.clinic_phone_no IS
    'the phone number of the clinic';

COMMENT ON COLUMN clinic.clinic_address IS
    'the address of the clinic';

COMMENT ON COLUMN clinic.vet_id IS
    'the vet id number';

CREATE UNIQUE INDEX clinic__idx ON
    clinic (
        vet_id
    ASC );

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE drug (
    drug_id              NUMBER(3) NOT NULL,
    drug_name            VARCHAR2(40) NOT NULL,
    drug_instruction     VARCHAR2(100) NOT NULL,
    drug_standard_charge NUMBER(5, 2) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'the drug id number';

COMMENT ON COLUMN drug.drug_name IS
    'the drug name';

COMMENT ON COLUMN drug.drug_instruction IS
    'the instructions of the drug';

COMMENT ON COLUMN drug.drug_standard_charge IS
    'the standard charge of the drug';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE owner (
    owner_id       NUMBER(3) NOT NULL,
    owner_giv_name VARCHAR2(30) NOT NULL,
    owner_fam_name VARCHAR2(30) NOT NULL,
    owner_phone_no NUMBER(10) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'the owner id number';

COMMENT ON COLUMN owner.owner_giv_name IS
    'the owner given name';

COMMENT ON COLUMN owner.owner_fam_name IS
    'the owner family name';

COMMENT ON COLUMN owner.owner_phone_no IS
    'the vet phone number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE pet (
    pet_id        NUMBER(5) NOT NULL,
    pet_name      VARCHAR2(20) NOT NULL,
    pet_born_year DATE NOT NULL,
    pet_status    CHAR(1) NOT NULL,
    owner_id      NUMBER(3) NOT NULL,
    pet_type_id   NUMBER(3) NOT NULL
);

ALTER TABLE pet
    ADD CHECK ( pet_status IN ( 'N', 'Y' ) );

COMMENT ON COLUMN pet.pet_id IS
    'the pet id number';

COMMENT ON COLUMN pet.pet_name IS
    'the pet name';

COMMENT ON COLUMN pet.pet_born_year IS
    'the born year of the pet';

COMMENT ON COLUMN pet.pet_status IS
    'pet status if the pet is alive of dead :(Y/yes) (N/no)';

COMMENT ON COLUMN pet.owner_id IS
    'the owner id number';

COMMENT ON COLUMN pet.pet_type_id IS
    'pet type id number ';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( pet_id );

CREATE TABLE pet_type (
    pet_type_id          NUMBER(3) NOT NULL,
    pet_type_name        VARCHAR2(50) NOT NULL,
    pet_type_description VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN pet_type.pet_type_id IS
    'pet type id number ';

COMMENT ON COLUMN pet_type.pet_type_name IS
    'the type name of the pet ';

COMMENT ON COLUMN pet_type.pet_type_description IS
    'the description of the pet type ';

ALTER TABLE pet_type ADD CONSTRAINT pet_type_pk PRIMARY KEY ( pet_type_id );

CREATE TABLE service (
    service_code            CHAR(5) NOT NULL,
    service_description     VARCHAR2(100) NOT NULL,
    service_standard_charge NUMBER(5, 2) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'service code number of the visit service';

COMMENT ON COLUMN service.service_description IS
    'description of the service during visit';

COMMENT ON COLUMN service.service_standard_charge IS
    'the standard charge of the service ';

ALTER TABLE service ADD CONSTRAINT visit_service_pk PRIMARY KEY ( service_code );

CREATE TABLE specialisation (
    spec_id           NUMBER(4) NOT NULL,
    spec_name         CHAR(50) NOT NULL,
    spec__description VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN specialisation.spec_id IS
    'SPECIALIZATION vet id number ';

COMMENT ON COLUMN specialisation.spec_name IS
    'SPECIALIZATION vet name';

COMMENT ON COLUMN specialisation.spec__description IS
    'vet SPECIALIZATION descripton ';

ALTER TABLE specialisation ADD CONSTRAINT specialization_pk PRIMARY KEY ( spec_id );

CREATE TABLE train_vet (
    train_id             NUMBER(3) NOT NULL,
    vet_id               NUMBER(2) NOT NULL,
    train_vet_completion CHAR(1) NOT NULL,
    train_vet_expiry     DATE NOT NULL
);

ALTER TABLE train_vet
    ADD CHECK ( train_vet_completion IN ( 'N', 'Y' ) );

COMMENT ON COLUMN train_vet.train_id IS
    'id number of training';

COMMENT ON COLUMN train_vet.vet_id IS
    'the vet id number';

COMMENT ON COLUMN train_vet.train_vet_completion IS
    'completion of the vet training:Y(yes)/N(no)';

COMMENT ON COLUMN train_vet.train_vet_expiry IS
    'expiry date of vet training';

ALTER TABLE train_vet ADD CONSTRAINT train_vet_pk PRIMARY KEY ( vet_id,
                                                                train_id );

CREATE TABLE training (
    train_id          NUMBER(3) NOT NULL,
    vet_id            NUMBER(2) NOT NULL,
    train_date_time   DATE NOT NULL,
    train_course_name VARCHAR2(40),
    train_duration    NUMBER(2),
    train_title       VARCHAR2(50) NOT NULL,
    clinic_id         NUMBER(2) NOT NULL
);

COMMENT ON COLUMN training.train_id IS
    'id number of training';

COMMENT ON COLUMN training.vet_id IS
    'the vet id number';

COMMENT ON COLUMN training.train_date_time IS
    'the training date and time';

COMMENT ON COLUMN training.train_course_name IS
    'the training course name';

COMMENT ON COLUMN training.train_duration IS
    'the training duration';

COMMENT ON COLUMN training.train_title IS
    'the training title';

COMMENT ON COLUMN training.clinic_id IS
    'the clinic id number';

ALTER TABLE training ADD CONSTRAINT training_pk PRIMARY KEY ( train_id );

ALTER TABLE training ADD CONSTRAINT training_uk UNIQUE ( vet_id,
                                                         train_date_time );

CREATE TABLE vet (
    vet_id            NUMBER(2) NOT NULL,
    vet_giv_name      VARCHAR2(30),
    vet_fam_name      VARCHAR2(30),
    vet_phone_no      NUMBER(10) NOT NULL,
    vet_employed_date DATE NOT NULL,
    clinic_id         NUMBER(2) NOT NULL,
    spec_id           NUMBER(4) NOT NULL
);

COMMENT ON COLUMN vet.vet_id IS
    'the vet id number';

COMMENT ON COLUMN vet.vet_giv_name IS
    'the given name of the vet';

COMMENT ON COLUMN vet.vet_fam_name IS
    'the family name of the vet';

COMMENT ON COLUMN vet.vet_phone_no IS
    'the phone number of the vet';

COMMENT ON COLUMN vet.vet_employed_date IS
    'the date when the vet got employed';

COMMENT ON COLUMN vet.clinic_id IS
    'the clinic id number';

COMMENT ON COLUMN vet.spec_id IS
    'SPECIALIZATION vet id number ';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    visit_id           NUMBER(10) NOT NULL,
    vet_id             NUMBER(2) NOT NULL,
    visit_date_time    DATE NOT NULL,
    visit_pet_weight   NUMBER(3, 2) NOT NULL,
    visit_length       NUMBER(2, 2) NOT NULL,
    visit_notes        VARCHAR2(50) NOT NULL,
    visit_total_amount NUMBER(5, 2) NOT NULL,
    visit_payment_type CHAR(1) NOT NULL,
    clinic_id          NUMBER(2) NOT NULL,
    first_visit_id     NUMBER(10),
    pet_id             NUMBER(5) NOT NULL
);

ALTER TABLE visit
    ADD CHECK ( visit_payment_type IN ( 'C', 'E' ) );

COMMENT ON COLUMN visit.visit_id IS
    'the id number of the visit — surrogate key';

COMMENT ON COLUMN visit.vet_id IS
    'the vet id number';

COMMENT ON COLUMN visit.visit_date_time IS
    'date and time of the visit';

COMMENT ON COLUMN visit.visit_pet_weight IS
    'weight of the pet during visit';

COMMENT ON COLUMN visit.visit_length IS
    'length of the visit';

COMMENT ON COLUMN visit.visit_notes IS
    'notes taken by vet during the visit';

COMMENT ON COLUMN visit.visit_total_amount IS
    'amount charged per visit';

COMMENT ON COLUMN visit.visit_payment_type IS
    'type of payment during visit: C(CASH)/E(EFT)';

COMMENT ON COLUMN visit.clinic_id IS
    'the clinic id number';

COMMENT ON COLUMN visit.first_visit_id IS
    'the id number of the visit — surrogate key';

COMMENT ON COLUMN visit.pet_id IS
    'the pet id number';

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_id );

ALTER TABLE visit ADD CONSTRAINT visit_uk UNIQUE ( vet_id,
                                                   visit_date_time );

CREATE TABLE visit_drug (
    drug_id              NUMBER(3) NOT NULL,
    visit_id             NUMBER(10) NOT NULL,
    visit_drug_dose      NUMBER(4) NOT NULL,
    visit_drug_frequency VARCHAR2(50) NOT NULL,
    visit_drug_qtysup    NUMBER(3) NOT NULL,
    visit_drug_linecost  NUMBER(5, 2) NOT NULL
);

COMMENT ON COLUMN visit_drug.drug_id IS
    'the drug id number';

COMMENT ON COLUMN visit_drug.visit_id IS
    'the id number of the visit — surrogate key';

COMMENT ON COLUMN visit_drug.visit_drug_dose IS
    'the prescribed drug dosage';

COMMENT ON COLUMN visit_drug.visit_drug_frequency IS
    'the frequency of drugs prescribed';

COMMENT ON COLUMN visit_drug.visit_drug_qtysup IS
    'quantity of drug supplied';

COMMENT ON COLUMN visit_drug.visit_drug_linecost IS
    'line cost during the visit for drugs';

ALTER TABLE visit_drug ADD CONSTRAINT visit_drug_pk PRIMARY KEY ( visit_id,
                                                                  drug_id );

CREATE TABLE visit_service (
    visit_id               NUMBER(10) NOT NULL,
    visit_service_linecost NUMBER(5, 2) NOT NULL,
    service_code           CHAR(5) NOT NULL
);

COMMENT ON COLUMN visit_service.visit_id IS
    'the id number of the visit — surrogate key';

COMMENT ON COLUMN visit_service.visit_service_linecost IS
    'line cost of service during visit';

COMMENT ON COLUMN visit_service.service_code IS
    'service code number of the visit service';

ALTER TABLE visit_service ADD CONSTRAINT visit_service_pkv1 PRIMARY KEY ( visit_id,
                                                                          service_code
                                                                          );

ALTER TABLE training
    ADD CONSTRAINT clinic_training FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE vet
    ADD CONSTRAINT clinic_vet FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE visit
    ADD CONSTRAINT clinic_visit FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE pet
    ADD CONSTRAINT owner_pet FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE pet
    ADD CONSTRAINT pet_type FOREIGN KEY ( pet_type_id )
        REFERENCES pet_type ( pet_type_id );

ALTER TABLE visit
    ADD CONSTRAINT pet_visit FOREIGN KEY ( pet_id )
        REFERENCES pet ( pet_id );

ALTER TABLE visit_service
    ADD CONSTRAINT service_visit_service FOREIGN KEY ( service_code )
        REFERENCES service ( service_code );

ALTER TABLE clinic
    ADD CONSTRAINT vet_clinic FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE vet
    ADD CONSTRAINT vet_specialization FOREIGN KEY ( spec_id )
        REFERENCES specialisation ( spec_id );

ALTER TABLE training
    ADD CONSTRAINT vet_training FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE train_vet
    ADD CONSTRAINT vet_trainingv2 FOREIGN KEY ( train_id )
        REFERENCES training ( train_id );

ALTER TABLE visit
    ADD CONSTRAINT vet_visit FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE train_vet
    ADD CONSTRAINT vet2_train FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit_drug
    ADD CONSTRAINT visit_drug2 FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE visit
    ADD CONSTRAINT visit_visit FOREIGN KEY ( first_visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE visit_drug
    ADD CONSTRAINT visit2_drug FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE visit_service
    ADD CONSTRAINT visitservicetaken FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             35
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

spool off
set echo off